### ISSUE TITLE
Remove unnecessary line from command: selectMenu

### ISSUE THREAD

**Issue by WilliamAcosta1** [ZumitoTeam/zumito-framework#57]
The following line in the command appears to be unnecessary:

```
async selectMenu({ path, interaction, client, framework, guildSettings }: SelectMenuParameters): Promise<void> {
}
```

It would be a good idea to remove this line from the framework, as it currently serves no purpose and does not impact the execution. Removing it will clean up the code and avoid potential confusion or errors.

**Comment by fernandomema** [comment]
done
